name: Update README
on:
  schedule: # Run workflow automatically
    - cron: '0 0 * * *' # Runs once a day
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly
permissions:
  contents: write # To write the generated contents to the readme

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub App token
        id: generate-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@v5
        with:
          token: ${{ steps.generate-token.outputs.token }}

      - name: Update blogs list
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: 'https://kittychiu.github.io/feed.xml'
          max_post_count: 4
          date_format: 'mmmm yyyy'
          template: '<li><a href="$url">$title</a>  <i>$date</i></li>'
          committer_username: "kittychiu[bot]"
          committer_email: '42864823+KittyChiu@users.noreply.github.com'
          commit_message: '[auto] doc: Updated README blog posts list'

      - name: Update readings list
        uses: zwacky/goodreads-profile-workflow@main
        with:
          goodreads_user_id: '78391748'
          shelf: 'currently-reading'
          max_books_count: '4'
          template: '<li><a href="$url">$title</a>  <i>by $author</i></li>'
